server:
  port: 80
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:${heroku.postgresql.ivory.url}
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${okta.id}
            client-secret: ${okta.secret}
        provider:
          okta:
            authorization-uri: https://dev-903534.okta.com/oauth2/v1/authorize
            token-uri: https://dev-903534.okta.com/oauth2/v1/token
            user-info-uri: https://dev-903534.okta.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://dev-903534.okta.com/oauth2/v1/keys
  flyway:
    locations: classpath:/migrations
